"""change updated_at column

Revision ID: 649467de7e3f
Revises: 79fd5106d9d4
Create Date: 2024-08-17 12:55:07.579001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649467de7e3f'
down_revision: Union[str, None] = '79fd5106d9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', sa.DATETIME(), nullable=False))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
