"""add update_ate colummn to todo table

Revision ID: c03289257760
Revises: 22e87ca04066
Create Date: 2025-01-06 21:46:31.431387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03289257760'
down_revision: Union[str, None] = '22e87ca04066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'update_ate')
    # ### end Alembic commands ###
